{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "account-service.fullname" . }}-postgres
  namespace: {{ .Values.Namespace }}
  labels:
    {{- include "account-service.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app: {{ include "account-service.fullname" . }}-postgres
  ports:
      - port: {{ .Values.database.port }}
        targetPort: postgres
        name: postgres
  {{- end }}