apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: User
  namespace: argocd
spec:
  project: default
  source:
    repoURL: oci://registry-1.docker.io/mahendra3
      chart: user-service
      targetRevision: 0.1.0
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true