---
- name: Trigger ArgoCD Deployment
  hosts: localhost
  gather_facts: false

  vars:
    argocd_server: "localhost:30531"
    argocd_app_name: "user-app"
    argocd_user: "{{ lookup('env', 'ARGOCD_USER') }}"
    argocd_pass: "{{ lookup('env', 'ARGOCD_PASS') }}"

  tasks:

    - name: Verify ArgoCD CLI installed
      command: argocd version --client
      changed_when: false

    - name: Login to ArgoCD
      command:
        cmd: >
          argocd login {{ argocd_server }} --username {{ argocd_user }}  --password {{ argocd_pass }}     --insecure
      changed_when: false

    - name: Sync ArgoCD application
      command:
        cmd: >
          argocd app sync {{ argocd_app_name }} --prune
      changed_when: false

    - name: Wait for application health
      command:
        cmd: >
          argocd app wait {{ argocd_app_name }} --health  --timeout 180
      changed_when: false

    - name: Get final application status
      command:
        cmd: >
          argocd app get {{ argocd_app_name }}
      register: final_status
      changed_when: false

    - name: Print final application status
      debug:
        var: final_status.stdout_lines