apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "user-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "user-service.selectorLabels" . | nindent 6 }}
  serviceAccountName: {{ .Values.serviceAccount.name | default (include "user-service.fullname" .) }}
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "user-service-role"
        vault.hashicorp.com/agent-inject-secret-db-creds: "secret/user-service/db-creds"
        "vault.hashicorp.com/agent-inject-template-db-creds": |
          {{- with secret \"secret/user-service/db-creds\" -}}
          export DB_USER=\"{{ .Data.data.DB_USER }}\"
          export DB_PASSWORD=\"{{ .Data.data.DB_PASSWORD }}\"
          {{- end }}"
        vault.hashicorp.com/agent-inject-command-db-creds: |
          #!/bin/sh
          set -e
          source /vault/secrets/db-creds
          java -jar /app/app.jar
      labels:
        {{- include "user-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "user-service.fullname" . }}-config
            - secretRef:
                name: {{ include "user-service.fullname" . }}-secret
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}