apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "elk.kibana.fullname" . }}
  namespace: {{ .Values.Namespace }}
  labels:
    app: kibana
    {{- include "elk.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.kibana.replicas }}
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: "{{ .Values.kibana.image.repository }}:{{ .Values.kibana.image.tag }}"
          ports:
            - containerPort: 5601
              name: http
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://{{ include "elk.elasticsearch.fullname" . }}:9200"
            - name: XPACK_SECURITY_ENABLED
              value: "false"
          resources:
            {{- toYaml .Values.kibana.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /api/status
              port: 5601
            initialDelaySeconds: 60
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /api/status
              port: 5601
            initialDelaySeconds: 90
            periodSeconds: 20
