apiVersion: v1
kind: Service
metadata:
  name: {{ include "elk.kibana.fullname" . }}
  namespace: {{ .Values.Namespace }}
  labels:
    app: kibana
    {{- include "elk.labels" . | nindent 4 }}
spec:
  type: {{ .Values.kibana.service.type }}
  selector:
    app: kibana
  ports:
    - name: http
      port: {{ .Values.kibana.service.port }}
      targetPort: 5601
