apiVersion: v1
kind: Service
metadata:
  name: {{ include "elk.logstash.fullname" . }}
  namespace: {{ .Values.Namespace }}
  labels:
    app: logstash
    {{- include "elk.labels" . | nindent 4 }}
spec:
  selector:
    app: logstash
  ports:
    - name: tcp-input
      port: {{ .Values.logstash.tcpPort }}
      targetPort: {{ .Values.logstash.tcpPort }}
      protocol: TCP
