{{- if .Values.vault.enabled }}

apiVersion: external-secrets.io/v1
kind: ClusterSecretStore

metadata:
  name: vault-backend-notification
  namespace: {{ .Values.Namespace }}

spec:
  provider:
    vault:
      server: {{ .Values.vault.server | quote }}
      path: "secret"
      version: "v2"

      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "bank-app-role"

          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets

  {{- end }}