{{- if .Values.vault.enabled }}

apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: budget-service-secret
  namespace: {{ .Values.Namespace }}

spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}

  secretStoreRef:
    name: vault-backend-budget
    kind: ClusterSecretStore

  target:
    name: budget-service-secret
    creationPolicy: Owner

  data:
    - secretKey: DB_USER
      remoteRef:
        key: {{ .Values.vault.secretPath }}
        property: username

    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.vault.secretPath }}
        property: password

  {{- end }}